version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Updating nodejs...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - javac --version
      - mvn --version
      - apt update
      - apt install ca-certificates
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -          
      - apt -y install nodejs
      - aws --version
      - npm --version
      - npm install -g serverless
  build:
    commands:
      - mvn clean install
      - sls deploy
      - free -h